package ar.edu.unlu.modelo;

public enum Evento {
    DECISION,JUGADORES_INGRESADOS,NOMBRE_JUGADOR,CANT_FICHAS_INICIALES,FICHAS_INICIALES,VALOR_CIEGAS,REPARTIR_CARTAS,MOSTRAR_CARTAS,APUESTA,CANT_DESCARTE,INDICES_DESCARTE,DEFINIR_GANADORES
}
