package ar.edu.unlu.modelo;

public enum Evento {
    CONFIGURAR,JUGADORES_INGRESADOS,CANT_JUGADORES,NOMBRE_JUGADOR,CANT_FICHAS_INICIALES,FICHAS_REPARTIDAS,FICHAS_INICIALES,VALOR_CIEGAS,REPARTIR_CARTAS,MOSTRAR_CARTAS,APUESTA,CANT_DESCARTE,INDICES_DESCARTE,DEFINIR_GANADORES
}
